-- Custom SQL migration file, put your code below! --
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS archetype
(
    id integer NOT NULL,
    weapon_id integer NOT NULL,
    hat_sprite_id integer,
    name text NOT NULL,
    description text NOT NULL,
    CONSTRAINT archetype_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "character"
(
    id integer NOT NULL,
    weapon_id integer NOT NULL,
    archetype_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    hostile boolean NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT character_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS character_effect
(
    character_id integer NOT NULL,
    effect_id integer NOT NULL,
    CONSTRAINT character_effect_pkey PRIMARY KEY (character_id, effect_id)
);

CREATE TABLE IF NOT EXISTS character_stage
(
    id integer NOT NULL,
    character_id integer NOT NULL,
    stage_id integer NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    start_x integer NOT NULL DEFAULT 0,
    start_y integer NOT NULL DEFAULT 0,
    CONSTRAINT character_stage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS level_up_bonus
(
    character_id integer NOT NULL,
    talent_id integer NOT NULL,
    stat_id integer NOT NULL,
    CONSTRAINT character_talent_pkey PRIMARY KEY (character_id, talent_id)
);

CREATE TABLE IF NOT EXISTS dialogue
(
    id integer NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    character_stage_id integer NOT NULL,
    CONSTRAINT dialogue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS effect
(
    id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    duration integer NOT NULL,
    strength integer NOT NULL,
    CONSTRAINT effect_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory_item
(
    item_id integer NOT NULL,
    inventory_id integer NOT NULL,
    amount integer NOT NULL DEFAULT 1,
    PRIMARY KEY (item_id, inventory_id)
);

CREATE TABLE IF NOT EXISTS item
(
    id integer NOT NULL,
    sprite_id integer NOT NULL,
    effect_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sprite
(
    id integer NOT NULL,
    path text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sprite_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stage
(
    id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT stage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stage_tile
(
    id integer NOT NULL,
    stage_id integer NOT NULL,
    tile_id integer NOT NULL,
    world_x integer NOT NULL,
    world_y integer NOT NULL,
    item_id integer,
    CONSTRAINT stage_tile_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS talent
(
    id integer NOT NULL,
    archetype_id integer NOT NULL,
    CONSTRAINT talent_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tile
(
    id integer NOT NULL,
    effect_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT tile_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS weapon
(
    id integer NOT NULL,
    sprite_id integer NOT NULL,
    damage integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    CONSTRAINT weapon_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS weapon_effect
(
    weapon_id integer NOT NULL,
    effect_id integer NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT weapon_effect_pkey PRIMARY KEY (weapon_id, effect_id)
);

CREATE TABLE IF NOT EXISTS stat
(
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    value integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS archectype_stat
(
    archetype_id integer NOT NULL,
    stat_id integer NOT NULL,
    PRIMARY KEY (archetype_id, stat_id)
);

CREATE TABLE IF NOT EXISTS inventory
(
    character_id integer NOT NULL,
    PRIMARY KEY (character_id)
);

ALTER TABLE IF EXISTS account
ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
REFERENCES "character" (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS archetype
ADD CONSTRAINT hat_sprite_fk FOREIGN KEY (hat_sprite_id)
REFERENCES sprite (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS archetype
ADD CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
REFERENCES weapon (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS "character"
ADD CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
REFERENCES archetype (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS "character"
ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
REFERENCES sprite (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS "character"
ADD CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
REFERENCES weapon (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS character_effect
ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
REFERENCES "character" (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS character_effect
ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
REFERENCES effect (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS character_stage
ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
REFERENCES "character" (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS character_stage
ADD CONSTRAINT stage_fk FOREIGN KEY (stage_id)
REFERENCES stage (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS level_up_bonus
ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
REFERENCES "character" (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS level_up_bonus
ADD CONSTRAINT talent_fk FOREIGN KEY (talent_id)
REFERENCES talent (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS level_up_bonus
ADD CONSTRAINT stat_fk FOREIGN KEY (stat_id)
REFERENCES stat (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS dialogue
ADD CONSTRAINT character_stage_fk FOREIGN KEY (character_stage_id)
REFERENCES character_stage (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS inventory_item
ADD CONSTRAINT item_fk FOREIGN KEY (item_id)
REFERENCES item (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS inventory_item
ADD CONSTRAINT inventory_fk FOREIGN KEY (inventory_id)
REFERENCES inventory (character_id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS item
ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
REFERENCES effect (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS item
ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
REFERENCES sprite (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS stage_tile
ADD CONSTRAINT stage_fk FOREIGN KEY (stage_id)
REFERENCES stage (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS stage_tile
ADD CONSTRAINT tile_fk FOREIGN KEY (tile_id)
REFERENCES tile (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS stage_tile
ADD CONSTRAINT item_fk FOREIGN KEY (item_id)
REFERENCES item (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS talent
ADD CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
REFERENCES archetype (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS tile
ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
REFERENCES effect (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS tile
ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
REFERENCES sprite (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS weapon
ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
REFERENCES sprite (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS weapon_effect
ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
REFERENCES effect (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS weapon_effect
ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
REFERENCES sprite (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS weapon_effect
ADD CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
REFERENCES weapon (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS archectype_stat
ADD CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
REFERENCES archetype (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS archectype_stat
ADD CONSTRAINT stat_fk FOREIGN KEY (stat_id)
REFERENCES stat (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;


ALTER TABLE IF EXISTS inventory
ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
REFERENCES "character" (id) MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION
NOT VALID;
