-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
DROP SCHEMA IF EXISTS worm_game_db CASCADE;
CREATE SCHEMA worm_game_db


CREATE TABLE IF NOT EXISTS  effect
(
    id integer GENERATED ALWAYS AS IDENTITY,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    duration integer NOT NULL,
    strength integer NOT NULL,
    CONSTRAINT effect_pkey PRIMARY KEY (id)
) 

CREATE TABLE IF NOT EXISTS  sprite
(
    id integer GENERATED ALWAYS AS IDENTITY,
    path text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sprite_pkey PRIMARY KEY (id)
) 

CREATE TABLE IF NOT EXISTS  stage
(
    id integer GENERATED ALWAYS AS IDENTITY,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT stage_pkey PRIMARY KEY (id)
) 

CREATE TABLE IF NOT EXISTS  stat
(
    id integer GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    description text NOT NULL,
    value integer NOT NULL,
    PRIMARY KEY (id)
) 

CREATE TABLE IF NOT EXISTS  item
(
    id integer GENERATED ALWAYS AS IDENTITY,
    sprite_id integer NOT NULL,
    effect_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id),
    CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    	REFERENCES  effect (id) ,
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES  sprite (id) 
) 

CREATE TABLE IF NOT EXISTS  tile
(
    id integer GENERATED ALWAYS AS IDENTITY,
    effect_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT tile_pkey PRIMARY KEY (id),
    CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    	REFERENCES  effect (id) ,
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES  sprite (id) 
) 

CREATE TABLE IF NOT EXISTS  weapon
(
    id integer GENERATED ALWAYS AS IDENTITY,
    sprite_id integer NOT NULL,
    damage integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    CONSTRAINT weapon_pkey PRIMARY KEY (id),
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES  sprite (id) 
) 

-- ARCHETYPE 
CREATE TABLE IF NOT EXISTS  archetype
(
    id integer GENERATED ALWAYS AS IDENTITY,
    weapon_id integer NOT NULL,
    hat_sprite_id integer,
    name text NOT NULL,
    description text NOT NULL,
    CONSTRAINT archetype_pkey PRIMARY KEY (id),
  	CONSTRAINT sprite_fk FOREIGN KEY (hat_sprite_id)
        REFERENCES  sprite (id),
  	CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    	REFERENCES  weapon (id)

) 

CREATE TABLE IF NOT EXISTS  talent
(
    id integer GENERATED ALWAYS AS IDENTITY,
    archetype_id integer NOT NULL,
    CONSTRAINT talent_pkey PRIMARY KEY (id),
    CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
    	REFERENCES  archetype (id)
) 

-- JOIN TABLE
CREATE TABLE IF NOT EXISTS  weapon_effect
(
    weapon_id integer NOT NULL,
    effect_id integer NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT weapon_effect_pkey PRIMARY KEY (weapon_id, effect_id),
    CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    	REFERENCES  effect (id) ,
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES  sprite (id) ,
    CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    	REFERENCES  weapon (id)
) 

-- CHARACTER
CREATE TABLE IF NOT EXISTS  "character"
(
    id integer GENERATED ALWAYS AS IDENTITY,
    weapon_id integer NOT NULL,
    archetype_id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    hostile boolean NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT character_pkey PRIMARY KEY (id),
          CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
    REFERENCES  archetype (id),

      CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES  sprite (id),

      CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    REFERENCES  weapon (id)


) 

CREATE TABLE IF NOT EXISTS  inventory
(
    character_id integer NOT NULL,
    PRIMARY KEY (character_id),
      CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES  "character" (id)
) 

CREATE TABLE IF NOT EXISTS  account
(
    id integer GENERATED ALWAYS AS IDENTITY,
    character_id integer NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    CONSTRAINT account_pkey PRIMARY KEY (id),
    CONSTRAINT character_fk FOREIGN KEY (character_id)
        REFERENCES  "character" (id)
) 



-- JOIN TABLES 
CREATE TABLE IF NOT EXISTS  character_effect
(
    character_id integer NOT NULL,
    effect_id integer NOT NULL,
    CONSTRAINT character_effect_pkey PRIMARY KEY (character_id, effect_id),

      CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES  "character" (id) ,
      CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    REFERENCES  effect (id) 
) 

CREATE TABLE IF NOT EXISTS  character_stage
(
    id integer GENERATED ALWAYS AS IDENTITY,
    character_id integer NOT NULL,
    stage_id integer NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    start_x integer NOT NULL DEFAULT 0,
    start_y integer NOT NULL DEFAULT 0,
    CONSTRAINT character_stage_pkey PRIMARY KEY (id),
      CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES  "character" (id), 
      CONSTRAINT stage_fk FOREIGN KEY (stage_id)
    REFERENCES  stage (id) 
) 



CREATE TABLE IF NOT EXISTS  archectype_stat
(
    id integer NOT NULL,
    sprite_id integer NOT NULL,
    effect_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id),
    CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    	REFERENCES worm_game_db.effect (id) ,
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES worm_game_db.sprite (id) 
);

CREATE TABLE IF NOT EXISTS worm_game_db.tile
(
    id integer NOT NULL,
    effect_id integer,
    name text COLLATE pg_catalog."default" NOT NULL,
    sprite_id integer NOT NULL,
    CONSTRAINT tile_pkey PRIMARY KEY (id),
    CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    	REFERENCES worm_game_db.effect (id) ,
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES worm_game_db.sprite (id) 
);

CREATE TABLE IF NOT EXISTS worm_game_db.weapon
(
    id integer NOT NULL,
    sprite_id integer NOT NULL,
    damage integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    CONSTRAINT weapon_pkey PRIMARY KEY (id),
    CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    	REFERENCES worm_game_db.sprite (id) 
);

-- ARCHETYPE 
CREATE TABLE IF NOT EXISTS worm_game_db.archetype
(
    id integer NOT NULL,
    weapon_id integer NOT NULL,
    hat_sprite_id integer,
    name text NOT NULL,
    description text NOT NULL,
    CONSTRAINT archetype_pkey PRIMARY KEY (id),
  	CONSTRAINT sprite_fk FOREIGN KEY (hat_sprite_id)
        REFERENCES worm_game_db.sprite (id),
  	CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    	REFERENCES worm_game_db.weapon (id)

);

CREATE TABLE IF NOT EXISTS worm_game_db.talent
(
    id integer NOT NULL,
    archetype_id integer NOT NULL,
    stat_id integer NOT NULL,
    PRIMARY KEY (archetype_id, stat_id),
    CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
    REFERENCES  archetype (id) ,
      CONSTRAINT stat_fk FOREIGN KEY (stat_id)
    REFERENCES  stat (id)
) 

CREATE TABLE IF NOT EXISTS  level_up_bonus
(
    character_id integer NOT NULL,
    talent_id integer NOT NULL,
    stat_id integer NOT NULL,
    CONSTRAINT character_talent_pkey PRIMARY KEY (character_id, talent_id),
    CONSTRAINT stat_fk FOREIGN KEY (stat_id)
    	REFERENCES  stat (id)
) 

CREATE TABLE IF NOT EXISTS  inventory_item
(
    item_id integer NOT NULL,
    inventory_id integer NOT NULL,
    amount integer NOT NULL DEFAULT 1,
    PRIMARY KEY (item_id, inventory_id),
          CONSTRAINT item_fk FOREIGN KEY (item_id)
    REFERENCES  item (id) ,
      CONSTRAINT inventory_fk FOREIGN KEY (inventory_id)
    REFERENCES  inventory (character_id)

) 

CREATE TABLE IF NOT EXISTS  stage_tile 
(
    id integer GENERATED ALWAYS AS IDENTITY,
    stage_id integer NOT NULL,
    tile_id integer NOT NULL,
    item_id integer,
    world_x integer NOT NULL,
    world_y integer NOT NULL,
    CONSTRAINT stage_tile_pkey PRIMARY KEY (id),

    CONSTRAINT tile_fk FOREIGN KEY (tile_id)
    	REFERENCES  tile (id) ,
    CONSTRAINT stage_fk FOREIGN KEY (stage_id)
    	REFERENCES  stage (id) ,
    CONSTRAINT item_fk FOREIGN KEY (item_id)
    	REFERENCES  item (id) 
)  

-- DIALOGUE
CREATE TABLE IF NOT EXISTS  dialogue
(
    id integer GENERATED ALWAYS AS IDENTITY,
    content text COLLATE pg_catalog."default" NOT NULL,
    character_stage_id integer NOT NULL,
    CONSTRAINT dialogue_pkey PRIMARY KEY (id),
      CONSTRAINT character_stage_fk FOREIGN KEY (character_stage_id)
    REFERENCES  character_stage (id)
) ;
END;


