-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."character"
(
    id integer NOT NULL,
    weapon_id integer NOT NULL,
    archetype_id integer NOT NULL,
    name text NOT NULL,
    hp integer NOT NULL,
    vision integer NOT NULL,
    move_speed integer NOT NULL DEFAULT 1,
    hostile boolean NOT NULL,
    sprite_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id integer NOT NULL,
    character_id integer NOT NULL,
    item_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stage
(
    id integer NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tile
(
    id integer NOT NULL,
    effect_id integer,
    name text NOT NULL,
    sprite_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.effect
(
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.weapon
(
    id integer NOT NULL,
    sprite_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.item
(
    id integer NOT NULL,
    sprite_id integer NOT NULL,
    effect_id integer,
    name text NOT NULL,
    description text NOT NULL,
    effect_duration integer NOT NULL DEFAULT 0,
    effect_strength integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.talent
(
    id integer NOT NULL,
    archetype_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.archetype
(
    id integer NOT NULL,
    weapon_id integer NOT NULL,
    sprite_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.account
(
    id integer NOT NULL,
    character_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.weapon_effect
(
    weapon_id integer NOT NULL,
    effect_id integer NOT NULL,
    sprite_id integer NOT NULL,
    PRIMARY KEY (weapon_id, effect_id)
);

CREATE TABLE IF NOT EXISTS public.character_effect
(
    character_id integer NOT NULL,
    effect_id integer NOT NULL,
    PRIMARY KEY (character_id, effect_id)
);

CREATE TABLE IF NOT EXISTS public.character_talent
(
    character_id integer NOT NULL,
    talent_id integer NOT NULL,
    PRIMARY KEY (character_id, talent_id)
);

CREATE TABLE IF NOT EXISTS public.character_stage
(
    id integer NOT NULL,
    character_id integer NOT NULL,
    stage_id integer NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    start_x integer NOT NULL DEFAULT 0,
    start_y integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stage_tile
(
    id integer NOT NULL,
    stage_id integer NOT NULL,
    tile_id integer NOT NULL,
    world_x integer NOT NULL,
    world_y integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sprite
(
    id integer NOT NULL,
    path text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dialogue
(
    id integer NOT NULL,
    content text NOT NULL,
    character_stage_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."character"
    ADD CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    REFERENCES public.weapon (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."character"
    ADD CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
    REFERENCES public.archetype (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."character"
    ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES public.sprite (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES public."character" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT item_fk FOREIGN KEY (item_id, None)
    REFERENCES public.item (id, None) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tile
    ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    REFERENCES public.effect (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tile
    ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES public.sprite (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.weapon
    ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES public.sprite (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    REFERENCES public.effect (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES public.sprite (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.talent
    ADD CONSTRAINT archetype_fk FOREIGN KEY (archetype_id)
    REFERENCES public.archetype (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.archetype
    ADD CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    REFERENCES public.weapon (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.archetype
    ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES public.sprite (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES public."character" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.weapon_effect
    ADD CONSTRAINT weapon_fk FOREIGN KEY (weapon_id)
    REFERENCES public.weapon (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.weapon_effect
    ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    REFERENCES public.effect (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.weapon_effect
    ADD CONSTRAINT sprite_fk FOREIGN KEY (sprite_id)
    REFERENCES public.sprite (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_effect
    ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES public."character" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_effect
    ADD CONSTRAINT effect_fk FOREIGN KEY (effect_id)
    REFERENCES public.effect (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_talent
    ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES public."character" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_talent
    ADD CONSTRAINT talent_fk FOREIGN KEY (talent_id)
    REFERENCES public.talent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_stage
    ADD CONSTRAINT character_fk FOREIGN KEY (character_id)
    REFERENCES public."character" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.character_stage
    ADD CONSTRAINT stage_fk FOREIGN KEY (stage_id)
    REFERENCES public.stage (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stage_tile
    ADD CONSTRAINT stage_fk FOREIGN KEY (stage_id)
    REFERENCES public.stage (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.stage_tile
    ADD CONSTRAINT tile_fk FOREIGN KEY (tile_id)
    REFERENCES public.tile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dialogue
    ADD CONSTRAINT character_stage_fk FOREIGN KEY (character_stage_id)
    REFERENCES public.character_stage (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;